version: 2.1

jobs:
  save_inventory:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name : "create inventory header"
          command: |
            echo "[all]" >> inventory
      - run:
          name: "Make request via aws cli and save output file in inventory."
          command: |
            aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --filters "Name=tag:Project,Values=udacity" \
            --output text >> inventory
      
      - persist_to_workspace:
          root: ~/
          paths:
            - inventory

workflows:
  my_workflow:
    jobs:
      - save_inventory