version: 2.1

jobs:
  smoke_test:
      docker:
        - image: circleci/python:3.8.3-buster
      steps:
        - run: apk add --update curl
        - run:
            name: smoke test.
            command: |
              URL="https://blog.udacity.com/"
              if curl -s --head ${URL} # test if blog.udacity. com exists
              then
               return 0
              else
               return 1
              fi

workflows:
  my_workflow:
    jobs:
      - smoke_test:
          requires:
            - configure_infrastructure